# Country and city data
COUNTRY_DATA = {
    'السودان': {'city': 'الخرطوم', 'airlines': ['الخطوط الجوية السودانية', 'بدر إيرلاينز', 'طيران تارجت']},
    'مصر': {'city': 'القاهرة', 'airlines': ['مصر للطيران', 'النيل للطيران', 'العربية للطيران - مصر']},
    'السعودية': {'city': 'الرياض', 'airlines': ['الخطوط السعودية', 'طيران ناس', 'طيران أديل']},
    'الإمارات': {'city': 'دبي', 'airlines': ['طيران الإمارات', 'الاتحاد للطيران', 'فلاي دبي']},
    'قطر': {'city': 'الدوحة', 'airlines': ['الخطوط الجوية القطرية']},
    'الكويت': {'city': 'الكويت', 'airlines': ['الخطوط الجوية الكويتية', 'جزيرة للطيران']},
    'البحرين': {'city': 'المنامة', 'airlines': ['طيران الخليج']},
    'عُمان': {'city': 'مسقط', 'airlines': ['الطيران العماني', 'سلام إير']},
    'الأردن': {'city': 'عمّان', 'airlines': ['الملكية الأردنية', 'العربية للطيران - الأردن']},
    'فلسطين': {'city': 'القدس', 'airlines': ['الخطوط الجوية الفلسطينية']},
    'لبنان': {'city': 'بيروت', 'airlines': ['طيران الشرق الأوسط']},
    'سوريا': {'city': 'دمشق', 'airlines': ['الخطوط الجوية السورية', 'شام وينگز']},
    'العراق': {'city': 'بغداد', 'airlines': ['الخطوط الجوية العراقية', 'طيران أور']},
    'اليمن': {'city': 'صنعاء', 'airlines': ['الخطوط الجوية اليمنية', 'يمنية فيلكس']},
    'ليبيا': {'city': 'طرابلس', 'airlines': ['الخطوط الجوية الليبية', 'أفريقيا للطيران']},
    'تونس': {'city': 'تونس', 'airlines': ['الخطوط التونسية', 'نوفل إير']},
    'الجزائر': {'city': 'الجزائر', 'airlines': ['الخطوط الجزائرية', 'طيران تسيرة']},
    'المغرب': {'city': 'الدار البيضاء', 'airlines': ['الخطوط الملكية المغربية', 'العربية للطيران - المغرب']},
    'موريتانيا': {'city': 'نواكشوط', 'airlines': ['موريتانيا للطيران']},
    'الصومال': {'city': 'مقديشو', 'airlines': ['الخطوط الصومالية', 'جوبا للطيران']},
    'جيبوتي': {'city': 'جيبوتي', 'airlines': ['جيبوتي للطيران']},
    'جزر القمر': {'city': 'موروني', 'airlines': ['القمرية للطيران']},
    'دولي': {'city': 'إسطنبول', 'airlines': ['الخطوط التركية', 'القطرية العالمية', 'الاتحاد الدولي']},
}

LOCAL_CITIES = {
    'السودان': ['ود مدني', 'بورتسودان', 'الأبيض', 'نيالا', 'كسلا', 'عطبرة', 'دنقلا', 'الفاشر', 'جنينة', 'كادوقلي'],
    'مصر': ['الإسكندرية', 'الأقصر', 'أسوان', 'شرم الشيخ', 'الغردقة', 'المنصورة', 'بورسعيد', 'السويس', 'أسيوط', 'قنا'],
    'السعودية': ['جدة', 'الدمام', 'المدينة المنورة', 'أبها', 'تبوك', 'الطائف', 'خميس مشيط', 'حائل', 'بريدة', 'نجران'],
    'الإمارات': ['أبوظبي', 'الشارقة', 'رأس الخيمة', 'العين', 'الفجيرة', 'أم القيوين', 'عجمان'],
    'قطر': ['الخور', 'الوكرة', 'الريان', 'مسيعيد', 'الدوحة الجديدة'],
    'الكويت': ['الجهراء', 'الأحمدي', 'الفروانية', 'حولي', 'مبارك الكبير'],
    'البحرين': ['المحرق', 'الرفاع', 'مدينة عيسى', 'الحد', 'سترة'],
    'عُمان': ['صلالة', 'صحار', 'نزوى', 'صور', 'إبراء', 'بركاء'],
    'الأردن': ['العقبة', 'إربد', 'الزرقاء', 'معان', 'الكرك'],
    'فلسطين': ['غزة', 'رام الله', 'الخليل', 'نابلس', 'بيت لحم', 'جنين'],
    'لبنان': ['طرابلس', 'صيدا', 'زحلة', 'النبطية', 'جونيه'],
    'سوريا': ['حلب', 'اللاذقية', 'حمص', 'حماة', 'دير الزور', 'السويداء'],
    'العراق': ['البصرة', 'أربيل', 'الموصل', 'النجف', 'كركوك', 'السليمانية'],
    'اليمن': ['عدن', 'الحديدة', 'المكلا', 'تعز', 'إب', 'ذمار'],
    'ليبيا': ['بنغازي', 'مصراتة', 'سبها', 'البيضاء', 'زوارة'],
    'تونس': ['صفاقس', 'سوسة', 'جربة', 'توزر', 'القيروان', 'بنزرت'],
    'الجزائر': ['وهران', 'قسنطينة', 'عنابة', 'ورقلة', 'بجاية', 'سطيف'],
    'المغرب': ['الرباط', 'مراكش', 'طنجة', 'أكادير', 'فاس', 'مكناس', 'وجدة'],
    'موريتانيا': ['نواذيبو', 'كيفة', 'روصو', 'آدرار'],
    'الصومال': ['هرجيسا', 'بوصاصو', 'كسمايو', 'بلدوين'],
    'جيبوتي': ['علي صبيح', 'تاجورة', 'أبخ'],
    'جزر القمر': ['موتسامودو', 'فومبوني', 'دوموني'],
    'دولي': ['أنقرة', 'إزمير', 'أنطاليا', 'إسطنبول'],
}

HOTEL_NAMES = {
    5: ['فندق النخيل الذهبي', 'قصر الواحة الفاخر', 'برج اللؤلؤة', 'فندق الماسة'],
    4: ['فندق الأفق', 'منتجع الشراع', 'فندق الياسمين', 'فندق السفير'],
    3: ['فندق المسافر', 'بيت الضيافة', 'فندق النجمة', 'فندق الراحة'],
}

ROOM_TYPES = [('غرفة مفردة', 1), ('غرفة مزدوجة', 2), ('جناح عائلي', 4)]

COUNTRIES = [c for c in COUNTRY_DATA.keys() if c != 'دولي'] + ['أخرى']

TICKET_CLASSES = [
    ('economy', 'الدرجة العادية'),
    ('second', 'الدرجة الثانية'),
    ('business', 'درجة رجال الأعمال والمستثمرين'),
    ('first', 'الدرجة الأولى'),
]

CLASS_LABELS = dict(TICKET_CLASSES)

# Translations
TRANSLATIONS = {
    'login': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'signup': {'ar': 'إنشاء حساب', 'en': 'Sign Up'},
    'logout': {'ar': 'خروج', 'en': 'Logout'},
    'home': {'ar': 'الرئيسية', 'en': 'Home'},
    'airlines': {'ar': 'شركات الطيران', 'en': 'Airlines'},
    'flights': {'ar': 'الرحلات', 'en': 'Flights'},
    'hotels': {'ar': 'الفنادق', 'en': 'Hotels'},
    'baggage': {'ar': 'الأمتعة والالتزام', 'en': 'Baggage & Policy'},
    'bookings': {'ar': 'حجوزاتي', 'en': 'My Bookings'},
    'my_bookings': {'ar': 'حجوزاتي', 'en': 'My Bookings'},
    'welcome': {'ar': 'وكالة الدواحي للسفر والسياحة', 'en': 'Dawahi Travel & Tourism Agency'},
    'brand': {'ar': 'وكالة الدواحي ✦', 'en': 'Dawahi Agency ✦'},
    'sub_brand': {'ar': 'للسفر والسياحة', 'en': 'Travel & Tourism'},
    'footer': {'ar': 'وكالة الدواحي للسفر والسياحة — رحلتك تبدأ من هنا', 'en': 'Dawahi Travel & Tourism — Your journey starts here'},
    'email': {'ar': 'البريد الإلكتروني', 'en': 'Email'},
    'password': {'ar': 'كلمة المرور', 'en': 'Password'},
    'username': {'ar': 'اسم المستخدم', 'en': 'Username'},
    'phone': {'ar': 'رقم الهاتف', 'en': 'Phone'},
    'country': {'ar': 'الدولة', 'en': 'Country'},
    'passport': {'ar': 'صورة جواز السفر الساري المفعول', 'en': 'Passport Photo (valid)'},
    'code': {'ar': 'كود الدعوة / التحقق (إن وجد)', 'en': 'Invitation / Verification Code (optional)'},
    'confirm_password': {'ar': 'إعادة كتابة كلمة المرور', 'en': 'Confirm Password'},
    'register': {'ar': 'تسجيل', 'en': 'Register'},
    'login_button': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'signup_button': {'ar': 'إنشاء حساب', 'en': 'Sign Up'},
    'search_button': {'ar': 'بحث', 'en': 'Search'},
    'confirm_booking': {'ar': 'تأكيد الحجز وإصدار التذكرة', 'en': 'Confirm Booking & Issue Ticket'},
    'download_pdf': {'ar': 'تحميل التذكرة PDF', 'en': 'Download PDF Ticket'},
    'cancel_booking': {'ar': 'إلغاء الحجز', 'en': 'Cancel Booking'},
    'select_room': {'ar': 'اختيار', 'en': 'Select'},
    'back': {'ar': 'رجوع', 'en': 'Back'},
    'already_have_account': {'ar': 'لديك حساب بالفعل؟', 'en': 'Already have an account?'},
    'no_account': {'ar': 'ليس لديك حساب؟', 'en': 'No account?'},
    'create_account': {'ar': 'إنشاء حساب جديد', 'en': 'Create New Account'},
    'login_success': {'ar': 'تم تسجيل الدخول بنجاح', 'en': 'Login successful'},
    'signup_success': {'ar': 'تم إنشاء الحساب بنجاح، الرجاء تسجيل الدخول', 'en': 'Account created successfully, please login'},
    'booking_confirmed': {'ar': 'تم تأكيد الحجز بنجاح', 'en': 'Booking confirmed successfully'},
    'booking_cancelled': {'ar': 'تم إلغاء الحجز', 'en': 'Booking cancelled'},
    'error_generic': {'ar': 'حدث خطأ', 'en': 'An error occurred'},
    'economy': {'ar': 'الدرجة العادية', 'en': 'Economy'},
    'second': {'ar': 'الدرجة الثانية', 'en': 'Second Class'},
    'business': {'ar': 'درجة رجال الأعمال', 'en': 'Business Class'},
    'first': {'ar': 'الدرجة الأولى', 'en': 'First Class'},
    'local': {'ar': 'محلي', 'en': 'Local'},
    'international': {'ar': 'دولي', 'en': 'International'},
    'page_login': {'ar': 'تسجيل الدخول', 'en': 'Login'},
    'page_signup': {'ar': 'إنشاء حساب', 'en': 'Sign Up'},
    'page_home': {'ar': 'الرئيسية', 'en': 'Home'},
    'page_airline': {'ar': 'شركة طيران', 'en': 'Airline'},
    'page_select_class': {'ar': 'اختيار الدرجة', 'en': 'Select Class'},
    'page_hotel_rooms': {'ar': 'غرف الفندق', 'en': 'Hotel Rooms'},
    'page_book_room': {'ar': 'حجز الغرفة', 'en': 'Book Room'},
    'page_booking_detail': {'ar': 'تفاصيل الحجز', 'en': 'Booking Details'},
    'page_my_bookings': {'ar': 'حجوزاتي', 'en': 'My Bookings'},
    'status_confirmed': {'ar': 'مؤكدة', 'en': 'Confirmed'},
    'status_cancelled': {'ar': 'ملغاة', 'en': 'Cancelled'},
    'flight_details': {'ar': 'تفاصيل الرحلة', 'en': 'Flight Details'},
    'hotel_booking': {'ar': 'حجز الفندق', 'en': 'Hotel Booking'},
    'total': {'ar': 'الإجمالي', 'en': 'Total'},
    'price': {'ar': 'السعر', 'en': 'Price'},
    'route': {'ar': 'الرحلة', 'en': 'Route'},
    'class': {'ar': 'الدرجة', 'en': 'Class'},
    'reference': {'ar': 'المرجع', 'en': 'Reference'},
    'issue_date': {'ar': 'تاريخ الإصدار', 'en': 'Issue Date'},
    'passenger_info': {'ar': 'معلومات المسافر', 'en': 'Passenger Info'},
    'flight_price': {'ar': 'سعر التذكرة', 'en': 'Flight Price'},
    'hotel_price': {'ar': 'سعر الفندق', 'en': 'Hotel Price'},
    'total_price': {'ar': 'الإجمالي', 'en': 'Total Price'},
    'no_bookings': {'ar': 'لا توجد حجوزات بعد', 'en': 'No bookings yet'},
    'details': {'ar': 'التفاصيل', 'en': 'Details'},
    'cancel': {'ar': 'إلغاء', 'en': 'Cancel'},
    'confirm_cancel': {'ar': 'هل أنت متأكد من الإلغاء؟', 'en': 'Are you sure you want to cancel?'},
    'theme_light': {'ar': 'نهاري', 'en': 'Light'},
    'theme_dark': {'ar': 'ليلي', 'en': 'Dark'},
    'language': {'ar': 'اللغة', 'en': 'Language'},
    'arabic': {'ar': 'عربية', 'en': 'Arabic'},
    'english': {'ar': 'إنجليزية', 'en': 'English'},
    'from_city': {'ar': 'من', 'en': 'From'},
    'to_city': {'ar': 'إلى', 'en': 'To'},
    'departure': {'ar': 'مغادرة', 'en': 'Departure'},
    'arrival': {'ar': 'وصول', 'en': 'Arrival'},
    'duration': {'ar': 'المدة', 'en': 'Duration'},
    'room_type': {'ar': 'نوع الغرفة', 'en': 'Room Type'},
    'capacity': {'ar': 'السعة', 'en': 'Capacity'},
    'price_per_night': {'ar': 'السعر لليلة', 'en': 'Price per night'},
    'checkin': {'ar': 'تاريخ الوصول', 'en': 'Check-in'},
    'checkout': {'ar': 'تاريخ المغادرة', 'en': 'Check-out'},
    'book_room': {'ar': 'حجز الغرفة', 'en': 'Book Room'},
    'airline': {'ar': 'شركة الطيران', 'en': 'Airline'},
    'select_class': {'ar': 'اختيار الدرجة', 'en': 'Select Class'},
    'passport_issue': {'ar': 'تاريخ إصدار جواز السفر', 'en': 'Passport Issue Date'},
    'passport_expiry': {'ar': 'تاريخ انتهاء جواز السفر', 'en': 'Passport Expiry Date'},
    'passport_expired': {'ar': 'جواز السفر منتهي الصلاحية! الرجاء استخدام جواز سفر ساري.', 'en': 'Passport expired! Please use a valid passport.'},
    'passport_invalid_dates': {'ar': 'تاريخ الإصدار لا يمكن أن يكون بعد تاريخ الانتهاء', 'en': 'Issue date cannot be after expiry date'},
    'invalid_date_format': {'ar': 'صيغة التاريخ غير صحيحة', 'en': 'Invalid date format'},
    'username_short': {'ar': 'اسم المستخدم يجب أن يكون 3 أحرف على الأقل', 'en': 'Username must be at least 3 characters'},
    'invalid_email': {'ar': 'البريد الإلكتروني غير صحيح', 'en': 'Invalid email address'},
    'invalid_phone': {'ar': 'رقم الهاتف يجب أن يكون 8 أرقام على الأقل', 'en': 'Phone must be at least 8 digits'},
    'password_short': {'ar': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل', 'en': 'Password must be at least 6 characters'},
    'passwords_mismatch': {'ar': 'كلمات المرور غير متطابقة', 'en': 'Passwords do not match'},
    'passport_required': {'ar': 'صورة جواز السفر مطلوبة', 'en': 'Passport photo is required'},
    'invalid_file_format': {'ar': 'صيغة الملف غير صحيحة. استخدم PNG أو JPG أو JPEG أو WebP', 'en': 'Invalid file format. Use PNG, JPG, JPEG or WebP'},
    'email_exists': {'ar': 'البريد الإلكتروني موجود بالفعل', 'en': 'Email already exists'},
    'invalid_checkout_date': {'ar': 'تاريخ المغادرة يجب أن يكون بعد تاريخ الوصول', 'en': 'Check-out date must be after check-in date'},
}
